[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fed"
version = "1.0.0"
description = "Federated Learning with Flower and PyTorch"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.18.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "numpy>=1.24.0",
    "wandb==0.19.11",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "David"

[tool.flwr.app.components]
serverapp = "fed.server_app:app"
clientapp = "fed.client_app:app"

[tool.flwr.app.config]
# Server configuration
run-name = "fed-server-test-r2"
num-server-rounds = 50
fraction-fit = 1.0
server_learning-rate = 0.01
seed = -1 # -1 for random seed

# Client configuration
local-epochs = 10
early-stopping = true
batch-size = 64 #20
client-learning-rate = 0.001 #0.0316
client-optimizer = "adam"

logger-type="file" # "file" or "wandb"
partitioning-strategy = "dirichlet"
dataset = "uoft-cs/cifar10"

# Optional partitioning parameters (uncomment as needed)
# For Dirichlet partitioning
dirichlet-alpha = 0.5
# For Pathological partitioning
# num_classes-per-partition = 2

# PARTITIONING_STRATEGIES = {
#    "iid": IidPartitioner,
#    "dirichlet": DirichletPartitioner,
#    "pathological": PathologicalPartitioner,
#    "shard": ShardPartitioner,
#    "size": SizePartitioner,
#    "linear": LinearPartitioner,
#    "square": SquarePartitioner,
#    "exponential": ExponentialPartitioner,
#}


[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 5